- package-lock.json
- package.json
- src/App.jsx
- src/App.module.scss
- src/components/Card.jsx
- src/components/index.jsx
- src/components/index.module.scss
- src/styles/_mixins.scss
> feat: card-component

- package-lock.json
- package.json
- src/App.jsx
- src/components/Hero/Hero.jsx
- src/components/Hero/index.jsx
- src/components/Hero/index.module.scss
> Feat: add hero component

- public/index.html
> fix:vercel_conflicts

- src/App.jsx
- src/components/ActivitiesHomeList/ActivitiesHomeList.jsx
- src/components/ActivitiesHomeList/index.jsx
- src/components/ActivitiesHomeList/index.module.scss
- src/components/ActivityHomeCard/ActivityHomeCard.jsx
- src/components/ActivityHomeCard/index.jsx
- src/components/ActivityHomeCard/index.module.scss
aggiunto il componente list delle attività in home.
creata la card delle attività in home con lo stile
> feat:activitiesHomeList-activityHomeCard

- src/components/Hero/Hero.jsx
- src/components/Hero/index.module.scss
> Feat: add-fetch-hero-component

- src/components/MainInput/MainInput.jsx
Aggiunto funzione - chiusura dell'input al click di un tag o classe diverso dall'input
> feat:add-function-input

- src/components/ActivityHomeCard/ActivityHomeCard.jsx
- src/components/ActivityHomeCard/index.module.scss
- src/components/CityCard/CityCard.jsx
- src/components/TopCityCardList/TopCityCardList.jsx
- src/pages/Activities/Activities.jsx
- src/pages/Activities/index.module.scss
- src/pages/Home/Home.jsx
- src/utils/api.js
> feat:addedd Activities page component

- src/components/ActivityHomeCard/ActivityHomeCard.jsx
- src/components/Hero/Hero.jsx
- src/index.js
- src/index.module.scss
- src/pages/Cities/Cities.jsx
- src/pages/Cities/index.jsx
- src/pages/Cities/index.module.scss
- src/utils/api.js
> Feat: add-city-page

- src/components/ActivityHomeCard/ActivityHomeCard.jsx
- src/components/ActivityHomeCard/index.module.scss
- src/pages/Activities/Activities.jsx
> Fix: activities-home-card

- src/components/CityCard/CityCard.jsx
- src/components/Hero/Hero.jsx
- src/pages/Cities/Cities.jsx
> Fix: width-img

- src/components/Header/Header.jsx
- src/components/Header/index.module.scss
- src/index.js
- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
> Feat:buy-button

- src/components/Header/Header.jsx
- src/components/Header/index.module.scss
- src/index.js
- src/pages/ActivityPage/ActivityPage.jsx
- src/store/index.js
> Feat:cart-logic

- src/components/Header/Header.jsx
> Fix:cart-logic

- src/components/Header/Header.jsx
> Fix:cart-item-number

- src/components/AttractionCard/AttractionCard.jsx
- src/components/AttractionCard/index.module.scss
- src/components/AttractionsList/AttractionsList.jsx
- src/components/AttractionsList/index.module.scss
- src/pages/Attractions/Attractions.jsx
- src/store/index.js
fetch per le liste most reviewed e highest average con map e dati passati come props
> feat:fetch-most-highest-attractions

- src/components/AirActivity/AirActivity.jsx
- src/components/AirActivity/index.jsx
- src/components/AirActivity/index.module.scss
- src/components/CardActivity/CardActivity.jsx
- src/components/CardActivity/index.jsx
- src/components/CardActivity/index.module.scss
- src/components/CityActivity/CityActivity.jsx
- src/components/CityActivity/index.jsx
- src/components/CityActivity/index.module.scss
- src/components/CruiseActivity/CruiseActivity.jsx
- src/components/CruiseActivity/index.jsx
- src/components/CruiseActivity/index.module.scss
- src/components/TopCityCardList/TopCityCardList.jsx
- src/index.js
- src/pages/Activities/Activities.jsx
- src/pages/Activities/index.module.scss
Create 3 new components (Air/City and CruiseActivity) and card for them
> feat add new lists in activity page

- package-lock.json
- package.json
- src/components/Hero/index.module.scss
- src/components/Map/Map.jsx
- src/components/Map/index.jsx
- src/components/Map/index.modules.scss
- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
- src/pages/Cities/Cities.jsx
> Fix:activity-page

- src/components/ActivityHomeCard/ActivityHomeCard.jsx
- src/components/Gallery/Gallery.jsx
- src/components/Header/Header.jsx
- src/pages/Cities/Cities.jsx
- src/pages/Cities/index.module.scss
> Fix:city-page-style

- src/components/Map/Map.jsx
- src/components/Map/index.modules.scss
- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
> Fix:cart-function

- src/components/AttractionCard/index.module.scss
- src/components/AttractionsList/index.module.scss
- src/pages/Attractions/Attractions.jsx
- src/pages/Attractions/index.module.scss
- src/store/index.js
- src/utils/countriesWithAttractions.js
c'è da fixare il modo in cui prende l'id per fare la get
> feat:countries-select-option-error-id-fetch

- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
- src/pages/Cities/Cities.jsx
> Fix:img-activity

- src/components/Map/Map.jsx
- src/components/Map/index.css
- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
> Fix:map-activity

- src/components/Map/index.css
- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
> Fix:map-activity-final

- README.md
- src/pages/Attractions/Attractions.jsx
- src/store/index.js
fixing fetch, deleted useState, added reducer in redux store
> fix:fixing-fetch-added-redux

- package-lock.json
- package.json
- src/components/ActivityHomeCard/ActivityHomeCard.jsx
- src/components/Map/Map.jsx
- src/components/Map/index.css
- src/components/Map/index.module.scss
- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
- src/pages/ActivityPage/mapbox.css
> Fix:map-activity-style

- src/components/Map/Map.jsx
- src/pages/ActivityPage/ActivityPage.jsx
> Fix :map visualization

- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
Fix:activity-page-style (nella pagina delle singole attività sono presenti due modelli di tasto "add to cart" per poter meglio sceglierne uno)
> Fix:activity-page-style

- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
> Fix:button-css

- README.md
- src/pages/ActivityPage/ActivityPage.jsx
> Fix:state-conflict

- src/pages/CartPage/CartPage.jsx
> fix:cart-total

- src/components/AttractionCard/AttractionCard.jsx
- src/components/AttractionCard/index.module.scss
- src/components/AttractionsList/AttractionsList.jsx
- src/components/AttractionsList/index.module.scss
- src/components/Footer/index.module.scss
- src/components/Header/Header.jsx
- src/components/MainInput/index.module.scss
- src/pages/Attractions/Attractions.jsx
- src/pages/Attractions/index.module.scss
> fix:solve-conflicts

- src/pages/ActivityPage/ActivityPage.jsx
- src/pages/ActivityPage/index.module.scss
- src/pages/CartPage/CartPage.jsx
- src/pages/CartPage/index.module.scss
> feat:ticket-number-animation

- src/components/CardActivity/CardActivity.jsx
- src/pages/ActivityPage/index.module.scss
- src/pages/CartPage/CartPage.jsx
> feat:disabled-button-logic

- src/components/Header/Header.jsx
- src/pages/ActivityPage/index.module.scss
- src/pages/CartPage/CartPage.jsx
> fix:cart-style

- src/pages/CartPage/CartPage.jsx
- src/pages/CartPage/index.module.scss
> fix:cart-button-style

- src/utils/api.js
> feat:language-header-fetch
